name: CI

on:
  push:
    branches:
      - "**" # This will trigger on all branches

jobs:
  build_and_lint_and_test:
    if: github.ref != 'refs/heads/main' # Only run on branches that are not main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [build, lint, test] # Define tasks to run in parallel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Run ${{ matrix.task }}
        run: npm run ${{ matrix.task }} # Execute the npm script defined in the strategy.matrix.tasks (e.g., build, lint, test)

  deploy:
    if: github.ref == 'refs/heads/main' # Only run on the main branch
    runs-on: ubuntu-latest

    # Here we could either add test, ts-check, es-lint... steps  or just do the build to keep it fast.
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Specify the Node.js version you want to use

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Deploy to Firebase
        run: |
          printf "%s" "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > $HOME/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"
          npx firebase-tools deploy --project 161916150055
